<section class="content">
  <div class="row">
    <div class="col-md-3">
      <div class="box box-primary">
        <div class="box-body box-profile">
          <img src="<?= $wwwUrl."/".$user['url'] ?>" class="profile-user-img img-responsive img-circle" alt="<?= $user['alt'] ?>">
          <h3 class="profile-username text-center">
            <?= $user['firstName']." ".$user['name'] ?>
          </h3>
          <ul class="list-group list-group-unbordered">
                <li class="list-group-item">
                  <b>Commandes</b> <a class="pull-right">60</a>
                </li>
                <li class="list-group-item">
                  <b>Points de fidélité</b> <a class="pull-right">543</a>
                </li>

          </ul>
        </div>
      </div>

    </div>
    <div class="col-md-9">
              <div class="nav-tabs-custom">
                <ul class="nav nav-tabs">
                  <li class="active"><a href="#activity" data-toggle="tab" aria-expanded="true">Activité</a></li>
                  <li class=""><a href="#timeline" data-toggle="tab" aria-expanded="false">Chronologie</a></li>
                  <li class=""><a href="#settings" data-toggle="tab" aria-expanded="false">Paramètres</a></li>
                  <li class=""><a href="#passwd" data-toggle="tab" aria-expanded="false">Mot de passe</a></li>
                </ul>

                <div class="tab-content">
                  <div class="tab-pane active" id="activity">
                    <!-- Post -->
                    <div class="post">
                      <div class="user-block">

                      </div>
                      <!-- /.user-block -->

                      <input class="form-control input-sm" type="text" placeholder="Type a comment">
                    </div>
                    <!-- /.post -->

                    <!-- Post -->
                    <div class="post clearfix">
                      <div class="user-block">

                      </div>
                      <!-- /.user-block -->

                      <form class="form-horizontal">
                        <div class="form-group margin-bottom-none">
                          <div class="col-sm-9">
                            <input class="form-control input-sm" placeholder="Response">
                          </div>
                          <div class="col-sm-3">
                            <button type="submit" class="btn btn-danger pull-right btn-block btn-sm">Envoyer</button>
                          </div>
                        </div>
                      </form>
                    </div>
                    <!-- /.post -->


                  </div>
                  <!-- /.tab-pane -->
                  <div class="tab-pane" id="timeline">
                    <!-- The timeline -->
                    <ul class="timeline timeline-inverse">
                      <!-- timeline time label -->

                      <!-- /.timeline-label -->
                      <!-- timeline item -->

                      <!-- END timeline item -->
                      <!-- timeline item -->

                      <!-- END timeline item -->
                      <!-- timeline item -->

                      <!-- END timeline item -->

                      <!-- END timeline item -->

                  </div>
                  <!-- /.tab-pane -->

                  <div class="tab-pane" id="settings">
                    <form class="form-horizontal" action="" name="updateUser" method="post" enctype="multipart/form-data">

                      <div class="form-group">
                        <label for="inputName" class="col-sm-2 control-label">Nom</label>
                          <div class="col-sm-10">
                            <input type="text" name="name" class="form-control" id="inputName" value=<?php
                            if (isset($user['name']))
                            {
                              echo($user['name']);
                            }
                            else
                            {
                              echo("'Nom'");
                            }
                             ?>>
                        </div>
                      </div>

                      <div class="form-group">
                        <label for="inputName" class="col-sm-2 control-label">Prénom</label>
                        <div class="col-sm-10">
                          <input type="text" name="firstName" class="form-control" id="inputName" value=<?php
                          if (isset($user['firstName']))
                          {
                            echo("'".$user['firstName']."'");
                          }
                          else
                          {
                            echo("'Prénom'");
                          }
                           ?>>
                        </div>
                      </div>

                      <div class="form-group">
                        <label for="inputName" class="col-sm-2 control-label">Adresse</label>
                        <div class="col-sm-10">
                          <input type="text" name="address" class="form-control" id="inputName" value=<?php
                          if (isset($user['address']))
                          {
                            echo("'".$user['address']."'");
                          }
                          else
                          {
                            echo("'Adresse'");
                          }
                           ?>>
                        </div>
                      </div>

                      <div class="form-group">
                        <label for="inputName" class="col-sm-2 control-label">Complément d'adresse</label>
                        <div class="col-sm-10">
                          <input type="text" name="address2" class="form-control" id="inputName" value=<?php
                          if (isset($user['address2']))
                          {
                            echo("'".$user['address2']."'");
                          }
                          else
                          {
                            echo("'Informations complémentaires'");
                          }
                            ?>>
                        </div>
                      </div>

                      <div class="form-group">
                        <label for="inputName" class="col-sm-2 control-label">Code Postal</label>
                        <div class="col-sm-10">
                          <input type="text" name="postCode" class="form-control" id="inputName" value=<?php
                          if (isset($user['postCode']))
                          {
                            echo($user['postCode']);
                          }
                          else
                          {
                            echo("'Code postal'");
                          }
                          ?>>
                        </div>
                      </div>

                      <div class="form-group">
                        <label for="inputName" class="col-sm-2 control-label">Ville</label>
                        <div class="col-sm-10">
                          <input type="text" name="city" class="form-control" id="inputName" value=<?php
                          if (isset($user['city']))
                          {
                            echo("'".$user['city']."'");
                          }
                          else
                          {
                            echo("'Ville'");
                          }
                          ?>>
                        </div>
                      </div>

                      <div class="form-group">
                        <label for="inputName" class="col-sm-2 control-label">Téléphone</label>
                        <div class="col-sm-10">
                          <input type="text" name="phone" class="form-control" id="inputName" value=<?php
                          if (isset($user['phone']))
                          {
                            echo("'".$user['phone']."'");
                          }
                          else
                          {
                            echo("+33");
                          }
                          ?>>
                        </div>
                      </div>

                      <div class="form-group">
                        <label for="inputEmail" class="col-sm-2 control-label">Email</label>
                        <div class="col-sm-10">
                          <input type="email" name="mail" class="form-control" id="inputEmail" value=<?php
                          if (isset($user['mail']))
                          {
                            echo("'".$user['mail']."'");
                          }
                          else
                          {
                            echo("'adresse mail'");
                          }
                          ?>>
                        </div>
                      </div>

                      <div class="form-group">
                        <label for="exampleInputFile" class="col-sm-2 control-label"></label>Avatar</label>
                        <div class="col-sm-10">
                        <input type="file" name="avatar" accept="image/*" id="exampleInputFile">
                        <p class="help-block">Ajouter votre photo de profil ! (fichier images uniquement)</p>
                      </div>
                      </div>
                      <div class="form-group">
                        <div class="col-sm-offset-2 col-sm-10">
                          <div class="checkbox">
                            <label>
                              <input required type="checkbox"><a href="#">termes et conditions</a>
                            </label>
                          </div>
                        </div>
                      </div>
                      <div class="form-group">
                        <div class="col-sm-offset-2 col-sm-10">
                          <button type="submit" class="btn btn-danger">Soumettre</button>
                        </div>
                      </div>
                    </form>
                  </div>

                  <div class="tab-pane" id="passwd">

                  </div>
                  <!-- /.tab-pane -->
                </div>
                <!-- /.tab-content -->
              </div>
              <!-- /.nav-tabs-custom -->
            </div>
  </div>

</section>
