<section class="content">
  <div class="row">
    <div class="col-md-3">
      <div class="box box-primary">
        <div class="box-body box-profile">
          <img src="<?= $wwwUrl ?>/images/user/1.jpg" class="profile-user-img img-responsive img-circle" alt="">
          <h3 class="profile-username text-center">
            David GERBER
          </h3>
          <ul class="list-group list-group-unbordered">
                <li class="list-group-item">
                  <b><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Abonnés </font></font></b> <a class="pull-right"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">1322</font></font></a>
                </li>
                <li class="list-group-item">
                  <b><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">À la suite de </font></font></b> <a class="pull-right"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">543</font></font></a>
                </li>
                <li class="list-group-item">
                  <b><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Amis </font></font></b> <a class="pull-right"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">13 287</font></font></a>
                </li>
          </ul>
        </div>
      </div>

    </div>
    <div class="col-md-9">
              <div class="nav-tabs-custom">
                <ul class="nav nav-tabs">
                  <li class="active"><a href="#activity" data-toggle="tab" aria-expanded="true"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Activité</font></font></a></li>
                  <li class=""><a href="#timeline" data-toggle="tab" aria-expanded="false"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Chronologie</font></font></a></li>
                  <li class=""><a href="#settings" data-toggle="tab" aria-expanded="false"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Paramètres</font></font></a></li>
                </ul>
                <div class="tab-content">
                  <div class="tab-pane active" id="activity">
                    <!-- Post -->
                    <div class="post">
                      <div class="user-block">

                      </div>
                      <!-- /.user-block -->

                      <input class="form-control input-sm" type="text" placeholder="Type a comment">
                    </div>
                    <!-- /.post -->

                    <!-- Post -->
                    <div class="post clearfix">
                      <div class="user-block">

                      </div>
                      <!-- /.user-block -->

                      <form class="form-horizontal">
                        <div class="form-group margin-bottom-none">
                          <div class="col-sm-9">
                            <input class="form-control input-sm" placeholder="Response">
                          </div>
                          <div class="col-sm-3">
                            <button type="submit" class="btn btn-danger pull-right btn-block btn-sm"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Envoyer</font></font></button>
                          </div>
                        </div>
                      </form>
                    </div>
                    <!-- /.post -->


                  </div>
                  <!-- /.tab-pane -->
                  <div class="tab-pane" id="timeline">
                    <!-- The timeline -->
                    <ul class="timeline timeline-inverse">
                      <!-- timeline time label -->
                      
                      <!-- /.timeline-label -->
                      <!-- timeline item -->

                      <!-- END timeline item -->
                      <!-- timeline item -->

                      <!-- END timeline item -->
                      <!-- timeline item -->

                      <!-- END timeline item -->

                      <!-- END timeline item -->

                  </div>
                  <!-- /.tab-pane -->

                  <div class="tab-pane" id="settings">
                    <form class="form-horizontal">
                      <div class="form-group">
                        <label for="inputName" class="col-sm-2 control-label"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">prénom</font></font></label>

                        <div class="col-sm-10">
                          <input type="email" class="form-control" id="inputName" placeholder="Name">
                        </div>
                      </div>
                      <div class="form-group">
                        <label for="inputEmail" class="col-sm-2 control-label"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Email</font></font></label>

                        <div class="col-sm-10">
                          <input type="email" class="form-control" id="inputEmail" placeholder="Email">
                        </div>
                      </div>
                      <div class="form-group">
                        <label for="inputName" class="col-sm-2 control-label"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">prénom</font></font></label>

                        <div class="col-sm-10">
                          <input type="text" class="form-control" id="inputName" placeholder="Name">
                        </div>
                      </div>
                      <div class="form-group">
                        <label for="inputExperience" class="col-sm-2 control-label"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Expérience</font></font></label>

                        <div class="col-sm-10">
                          <textarea class="form-control" id="inputExperience" placeholder="Experience"></textarea>
                        </div>
                      </div>
                      <div class="form-group">
                        <label for="inputSkills" class="col-sm-2 control-label"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Compétences</font></font></label>

                        <div class="col-sm-10">
                          <input type="text" class="form-control" id="inputSkills" placeholder="Skills">
                        </div>
                      </div>
                      <div class="form-group">
                        <div class="col-sm-offset-2 col-sm-10">
                          <div class="checkbox">
                            <label>
                              <input type="checkbox"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">J'accepte les </font></font><a href="#"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">termes et conditions</font></font></a>
                            </label>
                          </div>
                        </div>
                      </div>
                      <div class="form-group">
                        <div class="col-sm-offset-2 col-sm-10">
                          <button type="submit" class="btn btn-danger"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">Soumettre</font></font></button>
                        </div>
                      </div>
                    </form>
                  </div>
                  <!-- /.tab-pane -->
                </div>
                <!-- /.tab-content -->
              </div>
              <!-- /.nav-tabs-custom -->
            </div>
  </div>

</section>
