<div class="register-box">
  <div class="register-logo">
    <img src="<?= $wwwUrl ?>/images/logo-resto101.png" alt="">
  </div>
    <div class="register-box-body">
      <p>Enregistrez vous !</p>
      <form class="" action="<?= $requestUrl ?>/profile" method="post">
        <div class="form-group has-feedback">
          <input  class="form-control" type="text" name="" value="" placeholder="Nom Complet">
          <span class="glyphicon glyphicon-user form-control-feedback"></span>
        </div>
        <div class="form-group has-feedback">
          <input  class="form-control" type="text" name="" value="" placeholder="Email">
          <span class="glyphicon glyphicon-envelope form-control-feedback" ></span>
        </div>
        <div class="form-group has-feedback">
          <input  class="form-control" type="text" name="" value="" placeholder="Mot de Passe">
          <span class="glyphicon glyphicon-lock form-control-feedback" ></span>
        </div>
        <div class="form-group has-feedback">
            <input  class="form-control" type="text" name="" value="" placeholder="Retaper Mot de Passe">
          <span class="glyphicon glyphicon-log-in form-control-feedback" ></span>
        </div>

	<div class="form-group has-feedback">
            <input  class="form-control" type="submit" value="S'inscrire">
        </div>
      </form>
      <div class="social-auth-links text-center">
        <p>- ou -</p>
        <a href="#" class="btn btn-block btn-social btn-facebook btn-flat"><i class="fa fa-facebook"></i> Sign up using
        Facebook</a>
      </div>
      <a href="<?= $requestUrl?>/login">Vous ete deja menbre</a>
    </div>


</div>
