<form method="post" action="" enctype="multipart/form-data">
  <input type="text"  placeholder="Votre Prénom" name="firstName">
  <input type="password"  placeholder="password" name="password">
  <input type="lastName"  placeholder="Votre Nom de Famille" name="name">
  <input type="text"  placeholder="Votre adresse" name="adress">
  <input type="text" placeholder="Complément d'adresse" name="adress2">
  <input type="text" placeholder="Code Postal" name="postCode" minlength="5">
  <input type="text" placeHolder="Ville" name="city">
  <input type="tel"  placeholder="Votre numéro de téléphone" name="phone">
  <input type="mail" placeholder="Votre mail" name="mail">
  <input type="file" name="avatar" accept="image/*">
  <input type="submit">
</form>
