<!-- Message de notification -->

<!-- Code HTML à écrire -->


<!-- Liste des aliments -->
<section class="generic-table meal-list">
  <header>
    <section>
      <img src="<?= $wwwUrl ?>/images/home1.jpg" alt="">
    </section>
  </header>
  <section class="description">
    <cite>
      salut kiki
    </cite>
  </section>
    <tbody>
        <!-- Code HTML à écrire -->
    </tbody>
</section>
