<!-- Message de notification -->

<!-- Code HTML à écrire -->
    <section>
      <img class="img-resp" src="<?= $wwwUrl ?>/images/home1.jpg" alt="">
    </section>
<!-- Liste des aliments -->

  <section class="content">
      <div class="about-section">
			<!-- Container -->
			<div class="container">
				<!-- Row -->
				<div class="row">
					<div class="col-md-6 about-detail">
														<!-- Section Header -->
								<div class="section-header section-header2">
									<h3>About</h3>
                  <h4>Manger du code chez nous ça n'a pas de prix! </h4>
                </div><!-- Section Header /- -->
								<p>La recette, ou plutôt « les recettes » d'un projet de développement informatique doivent faire partie intégrante du projet.</p>
                <p>La recette doit être industrialisée, c'est à dire reposer sur des process clairement établis et documentés, et permettre de produire des résultats (rapports de test, création d'entrées dans un outil de ticketting, etc.) à partir d'un ensemble de données en entrée (cas de tests notamment).</p>
						<div class="chef-detail">
							<i><img  src="<?= $wwwUrl ?>/images/about-thumb.jpg" class="img-resp" alt=""></i>
              <span>
                <img src="<?= $wwwUrl ?>/images/chef-sign.png" class="img-resp" alt=""></span>
                <div class="cnt">
								<h4>JOHNY BIGOUDE</h4>
																				<ul>
											<li><a href="https://fr-fr.facebook.com/" target="_blank" title="Facebook"><i class="fa fa-facebook"></i></a></li>
                      <li><a href="https://twitter.com/" target="_blank" title="Twitter"><i class="fa fa-twitter"></i></a></li>
                      <li><a href="https://plus.google.com/discover" target="_blank" title="Google Plus"><i class="fa fa-google-plus"></i></a></li>										</ul>
																	</div>
						</div>
					</div>
					<div class="col-md-6 about-img-block no-padding">
						<div class="col-md-12 col-sm-6 col-xs-6">
								<img src="<?= $wwwUrl ?>/images/about-img1.jpg" class="img-resp" alt="">
            </div>
						<div class="col-md-12 col-sm-6 col-xs-6">
								<img src="<?= $wwwUrl ?>/images/about-img2.jpg" class="img-resp" alt="">
            </div>
					</div>
				</div><!-- Row /- -->
			</div><!-- Container /- -->
		</div>

  </section>
  <div class="background-section-command">
			<div class="surprise-content section-commandes text-center">
				<h3>Commander en ligne</h3>
												<a href="<?= $requestUrl ?>/menu">
							<img src="<?= $wwwUrl ?>/images/surprise-icon.png" class="suprise-content-img" alt="">						</a>
									</div>
		</div>
  <section>

  </section>

  <section class="services-section content">
    <div class="section-header text-center">
				<h3>Services</h3>
        <h4>NOS SPECIALITIES</h4>
    </div>
    <div class="row">
				<div class="col-md-3 col-sm-4 col-xs-6">
          <a href="<?= $requestUrl ?>/menu#menuEntree">
							<div class="srv-box">
								<div class="img-box">
									<img src="<?= $wwwUrl ?>/images/entree.jpg" class="img-resp" alt="" />
								</div>
								<h4>NOS ENTREES</h4>
              </div>
            </a>
						</div>

						<div class="col-md-3 col-sm-4 col-xs-6">
              <a href="<?= $requestUrl ?>/menu#menuplat">
							<div class="srv-box">
								<div class="img-box">
									<img src="http://lolthemes.com/demo/wpm/maxrestaurant/wp-content/uploads/2017/02/srv2.png" class="img-resp" alt="">
								</div>
								<h4>NOS PLATS</h4>
              </div>
            </a>
						</div>

						<div class="col-md-3 col-sm-4 col-xs-6">
              <a href="<?= $requestUrl ?>/menu#menudessert">
							<div class="srv-box">
								<div class="img-box">
									<img src="http://lolthemes.com/demo/wpm/maxrestaurant/wp-content/uploads/2017/02/srv3.png" class="img-resp" alt=""/>
								</div>
								<h4>NOS DESSERTS</h4>
              </div>
            </a>
						</div>

						<div class="col-md-3 col-sm-4 col-xs-6">
              <a href="<?= $requestUrl ?>/menu#menuboisson">
							<div class="srv-box">
								<div class="img-box">
									<img src="<?= $wwwUrl ?>/images/boisson.jpg" class="img-resp" alt=""/>
								</div>
								<h4>NOS BOISSONS</h4>
              </div>
            </a>
						</div>
				</div>
    </section>

  <section>
    <div class="bloc-nl">
      <h3 class="col-md-2 col-sm-6 col-xs-6">News Letters</h3>
      <p class="col-xs-3 ">Inscrivez-vous avec votre adresse mail pour recevoir des mises à jour de nos événements.</p>
      <div class="col-xs-4 input-group">
          <span class="input-group-addon"><i class="fa fa-envelope"></i></span>
          <input type="email" class="form-control" placeholder="Email">
      </div>
    </div>
  </section>
