<!-- Message de notification -->

<!-- Code HTML à écrire -->
    <section>
      <img class="img-resp" src="<?= $wwwUrl ?>/images/home1.jpg" alt="">
    </section>
<!-- Liste des aliments -->

  <section class="contenair">
    <section>
      <i class="fa fa-quote-left" aria-hidden="true"></i>
      <cite>
      Manger du code chez nous ça n'a pas de prix!
      </cite>
      <i class="fa fa-quote-right" aria-hidden="true"></i>
    </section>
  </section>
    <tbody>
        <!-- Code HTML à écrire -->
    </tbody>
