
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Resto 101</title>
    <link rel="stylesheet" href="<?= $wwwUrl ?>/css/normalize-3.0.3.min.css">
    <link rel="stylesheet" href="<?= $wwwUrl ?>/css/font-awesome-4.3.0.min.css">

    <!-- Feuilles de styles de l'application -->
    <link rel="stylesheet" href="<?= $wwwUrl ?>/css/3wa-resto.css">
    <link rel="stylesheet" href="<?= $wwwUrl ?>/css/ui-responsive.css">
    <link rel="stylesheet" href="<?= $wwwUrl ?>/dist/css/utilities.css">
    <link rel="stylesheet" href="<?= $wwwUrl ?>/bower_components/fullcalendar/dist/fullcalendar.min.css">
    <link rel="stylesheet" href="<?= $wwwUrl ?>/bower_components/fullcalendar/dist/fullcalendar.print.min.css" media="print">
    <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Oleo+Script+Swash+Caps|Karla">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Great+Vibes">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Raleway">


    <!-- Librairie jQuery -->



    <!-- JavaScript de l'application -->
    <script src="<?= $wwwUrl ?>/js/utilities.js"></script>
    <!-- jQuery 3 -->
    <script src="<?= $wwwUrl ?>/bower_components/jquery/dist/jquery.js"></script>
    <!-- Bootstrap 3.3.7-->
    <script src="<?= $wwwUrl ?>/bower_components/bootstrap/dist/js/bootstrap.min.js"></script>
    <!-- FastClick -->
    <script src="<?= $wwwUrl ?>/bower_components/fastclick/lib/fastclick.js"></script>
    <!-- AdminLTE App -->
    <script src="<?= $wwwUrl ?>/dist/js/adminlte.min.js"></script>
    <script src="<?= $wwwUrl ?>/bower_components/jquery-ui/jquery-ui.min.js"></script>
    <!-- Sparkline -->
    <script src="<?= $wwwUrl ?>/bower_components/jquery-sparkline/dist/jquery.sparkline.min.js"></script>
    <!-- jvectormap  -->
    <!-- SlimScroll -->
    <script src="<?= $wwwUrl ?>/bower_components/jquery-slimscroll/jquery.slimscroll.min.js"></script>
    <script src="<?= $wwwUrl ?>/bower_components/moment/moment.js"></script>
    <script src="<?= $wwwUrl ?>/bower_components/fullcalendar/dist/fullcalendar.js"></script>
    <!--<script src="/dist/js/pages/dashboard2.js"></script>-->
    <!-- AdminLTE for demo purposes -->
    <script src="<?= $wwwUrl ?>/dist/js/demo.js"></script>
    <!--<script src="<?= $wwwUrl ?>/js/sdk.js"></script>-->
</head>
<body>

  <header>
    <nav>
      <section class="content nav-top">
        <div>
          <a href="<?= $requestUrl ?>"><img style="width:30%;" src="<?= $wwwUrl ?>/images/logo-resto101.png" alt="101 Restaurant Logo"></a>
        </div>

              <?php
              if (isset($user))
              {
                if ($user['rights']=='Employed')
                {
                  include('Partiels/MenuViewAdmin.phtml');
                }
                else
                {
                  include('Partiels/MenuViewUser.phtml');
                }
              }
              else
              {
                  include('Partiels/MenuViewUser.phtml');
              }


              ?>

        <div>
          <?php if (isset($user))
          {
            include('Partiels/ProfileView.phtml');
          }
          else
          {
            include('Partiels/ConnectView.phtml');
          }?>
        </section>
      </nav>

        </div>
        <?php
        if (isset($_SESSION['flashbag']) && !empty($_SESSION['flashbag']))
        {
          if($flashbag->hasMessages() == true)
          {?>
            <aside  class="callout callout-danger" id="notice" class="notice">
                <?php foreach($flashbag->fetchMessages() as $message)
                { ?>
                  <p><?= $message ?></p>

                <?php
              } ?>
            </aside>
        <?php  }
      } ?>
  </header>
<!-- En-tête commune -->

<main>
    <!-- Affichage du template lié à la vue -->
    <?php include $this->viewData['template'] ?>
</main>

<!-- Pied de page commun -->
<footer>
   <section>
     <div class="col-xs-2 colum">
       <img class="img-resp mb20" src="<?= $wwwUrl ?>/images/logo-resto101-Blanc.png" alt="Resto 101">
       <p>46 Rue René Clair</p>
       <p>75018 Paris</p>
       <p>+33 (0) 1 75 43 42 42</p>
     </div>
     <div class="col-xs-3">
        <iframe src="https://www.google.fr/maps/d/embed?mid=1_8JIytSrEC12YOm56zIXKQUr7xFXd7Y7" width="400" height="300" frameborder="0" style="border:0;margin: 30px 0;"></iframe>
     </div>
     <div class="col-xs-2 colum">
       <p> Menu</p>
       <ul>
         <li></li>
       </ul>
     </div>
     <div class="col-xs-2 colum">
       <ul class="link-list">
           <li><img src="<?= $wwwUrl ?>/images/payment/visa.png" alt="Visa"></li>
           <li><img src="<?= $wwwUrl ?>/images/payment/mastercard.png" alt="MasterCard"></li>
           <li><img src="<?= $wwwUrl ?>/images/payment/paypal.png" alt="PayPal"></li>
       </ul>
     </div>
   </section>

    <small>Réalisé avec <i class="fa fa-heart"></i>&nbsp; par les élèves de la 3W Academy</small>
</footer>

<!-- Code principal JavaScript de l'application -->
<script src="<?= $wwwUrl ?>/js/main.js"></script>


</body>
</html>
