<div class="register-box">
    <div class="register-logo">
      <img class="img-resp" src="<?= $wwwUrl ?>/images/logo-resto101-Blanc.png" alt="Resto 101">
    </div>
    <div class="register-box-body">
      <p>Enregistrez un produit!</p>
      <form class="" action="<?= $requestUrl ?>/meal/createItem" method="post">
        <select class="" name="formItem">
          <option value="entrée">Entrée</option>
          <option value="plat">Plat</option>
          <option value="dessert">Dessert</option>
          <option value="boisson">Boisson</option>
          <option value="autre">Autre</option>
        </select>
        <div class="form-group has-feedback">
          <input  class="form-control" type="text" name="name" value="" placeholder="Nom du produit">
          <span class="glyphicon glyphicon-user form-control-feedback"></span>
        </div>
        <div class="form-group has-feedback">
          <textarea  class="form-control" type="text" name="description" value="" placeholder="Description du produit"></textarea>
          <span class="glyphicon glyphicon-user form-control-feedback"></span>
        </div>
        <div class="form-group has-feedback">
          <input  class="form-control" type="text" name="url" value="" placeholder="url photo">
          <span class="glyphicon glyphicon-envelope form-control-feedback" ></span>
        </div>
        <div class="form-group has-feedback">
          <input  class="form-control" type="text" name="alt" value="" placeholder="Desription photo">
          <span class="glyphicon glyphicon-envelope form-control-feedback" ></span>
        </div>
        <div class="form-group has-feedback">
          <input  class="form-control" type="text" name="buyPrice" value="" placeholder="Prix d'achat">
          <span class="glyphicon glyphicon-envelope form-control-feedback" ></span>
        </div>
        <div class="form-group has-feedback">
          <input  class="form-control" type="text" name="quantityStock" value="" placeholder="Quantité en stock">
          <span class="glyphicon glyphicon-lock form-control-feedback" ></span>
        </div>
        <div class="form-group has-feedback">
            <input  class="form-control" type="text" name="salePrice" value="" placeholder="Prix de vente">
          <span class="glyphicon glyphicon-log-in form-control-feedback" ></span>
        </div>
        <select class="" name="formItem">
          <option value="1">Visible</option>
          <option value="0">Non visible</option>
        </select>


	<div class="form-group has-feedback">
            <input  class="form-control" type="submit" value="Enregistrer">
        </div>
      </form>
