<!-- Main content -->
<section class="invoice">
  <!-- title row -->
  <div class="row">
    <div class="col-xs-12">
      <h2 class="page-header">
        <i class="fa fa-globe"></i> Restaurant101

      </h2>
    </div>
    <!-- /.col -->
  </div>
  <!-- info row -->
  <div class="row invoice-info">
    <div class="col-sm-4 invoice-col">
      De
      <address>
        <strong>Restaurant 101</strong><br>
        rue René Claire<br>
        75018 PARIS<br>
        Phone: none<br>
        Email: contact@restaurant101.fr
      </address>
    </div>
    <!-- /.col -->
    <div class="col-sm-4 invoice-col">
      A
      <address>
        <strong><?= $user['firstName']." ".$user['name']?></strong><br>
        <?= $user["address"]?><br>
        <?= $user["address2"]?><br>
        <?= $user["phone"]?><br>
        <?= $user["mail"]?>
      </address>
    </div>
    <!-- /.col -->

  </div>
  <!-- /.row -->

  <!-- Table row -->
  <div class="row">
    <div class="col-xs-12 table-responsive">
          <?php

        if (isset($cart))
        {
          foreach($cart as $key=>$value)
          {
            include(__DIR__."/../Partiels/CartTheadView.phtml");
            include(__DIR__."/../Partiels/CartItemView.phtml");
            echo("</tbody><table>");
          }
        }
        else
        {
          echo('<p>Votre panier est vide</p>');
        }


           ?>
    </div>
    <!-- /.col -->
  </div>
  <!-- /.row -->

  <div class="row">
    <!-- accepted payments column -->
    <div class="col-xs-6">
      <p class="lead">Moyen de paiement:</p>
      <img src="<?= $wwwUrl ?>/dist/img/credit/visa.png" alt="Visa">
      <img src="<?= $wwwUrl ?>/dist/img/credit/mastercard.png" alt="Mastercard">
      <img src="<?= $wwwUrl ?>/dist/img/credit/american-express.png" alt="American Express">
      <img src="<?= $wwwUrl ?>/dist/img/credit/paypal2.png" alt="Paypal">

      <p class="text-muted well well-sm no-shadow" style="margin-top: 10px;">
        J'ai tellement faim que je veux payer tout de suite !
      </p>
    </div>
    <!-- /.col -->
    <div class="col-xs-6">

      <div class="table-responsive">
        <table class="table">
          <tr>
            <th style="width:50%">Total des achats :</th>
            <td><span class="subTotal"></span> €</td>
          </tr>
          <tr>
            <th>TVA (20%)</th>
            <td><span class="subTotalTva"></span> €</td>
          </tr>
          <tr>
            <th>Frais de Livraisons:</th>
            <td>5.80€</td>
          </tr>
          <tr>
            <th>Total:</th>
            <td><span class="total"></span> €</td>
          </tr>
        </table>
      </div>
    </div>
    <!-- /.col -->
  </div>
  <!-- /.row -->

  <!-- this row will not appear when printing -->
  <div class="row no-print">
    <div class="col-xs-12">
      <a href="invoice-print.html" target="_blank" class="btn btn-default"><i class="fa fa-print"></i> Imprimer</a>
      <a href='<?= $requestUrl?>/panier/addorder'><button type='button' class='btn btn-success pull-right'><i class='fa fa-credit-card'></i> Payer
        </button>
      </a>
        <button type="button" class="btn btn-primary pull-right" style="margin-right: 5px;">
        <i class="fa fa-download"></i> Génerer PDF
      </button>
    </div>
  </div>
</section>
<!-- /.content -->
<div class="clearfix"></div>
<script src="<?= $wwwUrl?>/js/main.js"></script>
<script src="<?= $wwwUrl?>/js/ajaxCart.js"></script>
