<div class="register-box">
    <div class="register-logo">
      <img class="img-resp" src="<?= $wwwUrl ?>/images/logo-resto101-Blanc.png" alt="Resto 101">
    </div>
    <div class="register-box-body">
      <p>Enregistrez vous !</p>
      <form class="" action="<?= $requestUrl ?>/user/registre" method="post">
        <div class="form-group has-feedback">
          <input  class="form-control" type="text" name="firstName" value="" placeholder="Prénom">
          <span class="glyphicon glyphicon-user form-control-feedback"></span>
        </div>
        <div class="form-group has-feedback">
          <input  class="form-control" type="text" name="name" value="" placeholder="Nom">
          <span class="glyphicon glyphicon-user form-control-feedback"></span>
        </div>
        <div class="form-group has-feedback">
          <input  class="form-control" type="text" name="mail" value="" placeholder="Email">
          <span class="glyphicon glyphicon-envelope form-control-feedback" ></span>
        </div>
        <div class="form-group has-feedback">
          <input  class="form-control" type="text" name="password" value="" placeholder="Mot de Passe">
          <span class="glyphicon glyphicon-lock form-control-feedback" ></span>
        </div>
        <div class="form-group has-feedback">
            <input  class="form-control" type="text" name="passwordControl" value="" placeholder="Retaper Mot de Passe">
          <span class="glyphicon glyphicon-log-in form-control-feedback" ></span>
        </div>

	<div class="form-group has-feedback">
            <input  class="form-control" type="submit" value="S'inscrire">
        </div>
      </form>
      <div class="social-auth-links text-center">
        <p>- ou -</p>
        <!-- <a href="#" class="btn btn-block btn-social btn-facebook btn-flat"><i class="fa fa-facebook"></i> Sign up using -->
        <!-- Facebook</a> -->

        <div class="fb-login-button" data-max-rows="1" data-size="large" data-button-type="continue_with" data-show-faces="false" data-auto-logout-link="false" data-use-continue-as="true"></div>
      <p>
        Vous etes déjà membre ? Connectez-vous en haut de la page.
      </p>
    </div>


</div>
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = 'https://connect.facebook.net/fr_FR/sdk.js#xfbml=1&version=v2.11&appId=1159814964151481';
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>
