<div class="dropdown tasks-menu">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown">
    <i class="fa fa-shopping-cart" aria-hidden="true"></i>
  </a>
  <ul class="dropdown-menu">
    <li class="header"><h3>Panier</h3></li>
    <li>
      <!-- inner menu: contains the actual data -->
      <ul class="menu">
        <li><!-- Task item -->
          <a href="<?= $requestUrl ?>/panier">
              Liste Reservation
          </a>
        </li>
        <!-- end task item -->
        <li>
            <a href="<?= $requestUrl ?>/panier">voir mon panier</a>
            <a href="#">25 € TTC</a>
        </li>
        <!-- end task item -->
      </ul>
    </li>
  </ul>

</div>
