<div class="dropdown user user-menu menu-top">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown">

    <span class="hidden-xs">Se connecter</span>
  </a>
  <div class="dropdown-menu">
    <!-- User image -->
    <li class="user-header">

    </li>
    <!-- Menu Body -->
    <form method="post" action="<?= $requestUrl ?>/login">
    <div class="box-body">
      <div class="form-group">
        <label for="">Address email</label>
        <input type="email" name="email" class="form-control" id="exampleInputEmail1" placeholder="Enter email" data-com.agilebits.onepassword.user-edited="yes">
      </div>
      <div class="form-group">
        <label for="">Mot de passe</label>
        <input type="password" name="passwd" class="form-control" id="exampleInputPassword1" placeholder="Password" data-com.agilebits.onepassword.user-edited="yes">
      </div>
      <div class="row">
        <div class="col-xs-4 text-center">
          <input type="submit" value="Log-in">
        </div>
        <div class="col-xs-4 text-center">
          <a href="<?= $requestUrl?>/registre">S'incscrie</a>
        </div>
      </div>
    </li>
  </form>
</div>
