<div class="modal fade" id="modal-default<?= $value['id'] ?>">
         <div class="modal-dialog">
           <div class="modal-content">
             <div class="modal-header">
               <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                 <span aria-hidden="true">&times;</span></button>
               <h4 class="modal-title">Résumé de commande</h4>
             </div>
             <div class="modal-body">
               <?php
                 include('DashboardOrderDetailThead.phtml');

                 foreach($value['orderDetails'] as $innerKey=>$innerValue)
                 {
                   include('DashboardOrderDetailList.phtml');
                 }
                 echo('</tbody></table>');
               ?>
           </div>
           <!-- /.modal-content -->
         </div>
         <!-- /.modal-dialog -->
       </div>
</div>
