<div class="row">
    <!-- Menu Item -->
      <div class="col-md-6">
        <div class="menu-item">
          <div class="item-thumb">
              <i><img src="<?= $wwwUrl.$meal['url'] ?>" class="img-responsive" alt="<?= $meal['alt'] ?>"></i>
            </div>
            <h3><?= $meal['name'] ?><span><?= $meal['description']?></span></h3>
            <span><sup>€</sup><?= $meal['salePrice'] ?></span>
          </div>
      </div>
