    <!-- Menu Item -->
      <div class="col-md-6">
        <div class="menu-item">
          <div class="item-thumb">
              <i><img src="<?= $wwwUrl."/".$mealValue['url'] ?>" class="img-responsive img-menu" alt="<?= $mealValue['alt'] ?>"></i>
            </div>
            <h3><?= $mealValue['name'] ?><span><?= $mealValue['description']?></span></h3>
            <span><sup>€</sup><?= $mealValue['salePrice'] ?><a href=""><i class="fa fa-cart-arrow-down" aria-hidden="true"></i></a></span>
          </div>
      </div>
