
  <div class="dropdown tasks-menu">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
      Client
    </a>
    <ul class="dropdown-menu">
      <li class="header"><h3>Admin Client</h3></li>
      <li>
        <!-- inner menu: contains the actual data -->
        <ul class="menu">
          <li><!-- Task item -->
            <a href=<"<?= $requestUrl ?>/menu">
                Liste Client
            </a>
          </li>
          <!-- end task item -->
          <li><!-- Task item -->
            <a href="<?= $requestUrl ?>/dashboard/clients">
                Liste Commande
            </a>
          </li>
          <li><!-- Task item -->
            <a href="<?= $requestUrl ?>/dashboard/clients">
                Liste Reservation
            </a>
          </li>
          <!-- end task item -->
          <!-- end task item -->
        </ul>
      </li>
    </ul>
  </div>

  <div class="dropdown tasks-menu">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
      Page
    </a>
    <ul class="dropdown-menu">
      <li class="header"><h3>Modification des pages</h3></li>
      <li>
        <!-- inner menu: contains the actual data -->
        <ul class="menu">
          <li><!-- Task item -->
            <a href=<"<?= $requestUrl ?>/Commande">
                Home
            </a>
          </li>
          <!-- end task item -->
          <li><!-- Task item -->
            <a href="<?= $requestUrl ?>/dashboard/clients">
                Reserver
            </a>
          </li>
          <li><!-- Task item -->
            <a href="<?= $requestUrl ?>/dashboard/clients">
                Commander
            </a>
          </li>
          <li><!-- Task item -->
            <a href="<?= $requestUrl ?>/dashboard/clients">
                La Carte
            </a>
          </li>
          <li><!-- Task item -->
            <a href="<?= $requestUrl ?>/dashboard/clients">
                Contact
            </a>
          </li>
          <!-- end task item -->
          <!-- end task item -->
        </ul>
      </li>
    </ul>
  </div>

  <div class="dropdown tasks-menu">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
      Bibliothéque
    </a>
    <ul class="dropdown-menu">
      <li class="header"><h3>Ajouter des item</h3></li>
      <li>
        <!-- inner menu: contains the actual data -->
        <ul class="menu">
          <li><!-- Task item -->
            <a href=<"<?= $requestUrl ?>/Commande">
                Produit
            </a>
          </li>
          <!-- end task item -->
          <li><!-- Task item -->
            <a href="<?= $requestUrl ?>/dashboard/clients">
                Photo
            </a>
          </li>
          <li><!-- Task item -->
            <a href="<?= $requestUrl ?>/dashboard/clients">
                Commentaire
            </a>
          <!-- end task item -->
          <!-- end task item -->
        </ul>
      </li>
    </ul>
    <div class="form-group">
      <input type="text" class="form-control" id="navbar-search-input" placeholder="Search">
    </div>
  </div>
