<div class="dropdown tasks-menu">
  <a href="<?= $requestUrl ?>/menu" class="dropdown-toggle" >
    Reserver
  </a>
</div>
<div class="dropdown tasks-menu">
  <a href="<?= $requestUrl ?>/menu" class="dropdown-toggle" >
  Commander
  </a>
</div>
<div class="dropdown tasks-menu">
  <a href="<?= $requestUrl ?>/menu" class="dropdown-toggle" >
    La carte
  </a>
</div>
<div class="dropdown tasks-menu">
  <a href="<?= $requestUrl ?>/menu" class="dropdown-toggle" >
    Contact
  </a>
  <!--<form class="navbar-form navbar-left" role="search">
    <div class="form-group">
      <input type="text" class="form-control" id="navbar-search-input" placeholder="Search">
    </div>
  </form>-->
</div>

<div class="dropdown tasks-menu">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown">
    <i class="fa fa-shopping-cart" aria-hidden="true"></i>
  </a>
  <ul class="dropdown-menu">
    <li class="header"><h3>Panier</h3></li>
    <li>
      <!-- inner menu: contains the actual data -->
      <ul class="menu">
        <li><!-- Task item -->
          <a href="<?= $requestUrl ?>/panier">
              Liste Reservation
          </a>
        </li>
        <!-- end task item -->
        <li>
            <a href="<?= $requestUrl ?>/panier">voir mon panier</a>
            <a href="#">25 € TTC</a>
        </li>
        <!-- end task item -->
      </ul>
    </li>
  </ul>

</div>
