<div class="user-menu menu-top">
  <a href="<?= $requestUrl ?>/menu">
    <span class="hidden-xs">Reserver</span>
  </a>
  <a href="<?= $requestUrl ?>/menu">
    <span class="hidden-xs">Commander</span>
  </a>
  <a href="<?= $requestUrl ?>/menu">
    <span class="hidden-xs">La carte</span>
  </a>
  <a href="<?= $requestUrl ?>/menu">
    <span class="hidden-xs">Contact</span>
  </a>
  <form class="navbar-form navbar-left" role="search">
    <div class="form-group">
      <input type="text" class="form-control" id="navbar-search-input" placeholder="Search">
    </div>
  </form>
</div>
