<div class="dropdown tasks-menu">
  <a href="<?= $requestUrl ?>/dashboard/" class="dropdown-toggle">
    Dashboard
  </a>
</div>

</div>
  <div class="dropdown tasks-menu">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
      Client
    </a>
    <ul class="dropdown-menu">
      <li class="header"><h3>Admin Client</h3></li>
      <li>
        <!-- inner menu: contains the actual data -->
        <ul class="menu">
          <li><!-- Task item -->
            <a href=<"<?= $requestUrl ?>/dashboard/clients">
                Liste Client
            </a>
          </li>
          <!-- end task item -->
          <li><!-- Task item -->
            <a href="<?= $requestUrl ?>/dashboard/commandes">
                Liste Commande
            </a>
          </li>
          <li><!-- Task item -->
            <a href="<?= $requestUrl ?>/dashboard/Reservation">
                Liste Reservation
            </a>
          </li>
          <!-- end task item -->
          <!-- end task item -->
        </ul>
      </li>
    </ul>
  </div>

  <div class="dropdown tasks-menu">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
      Page
    </a>
    <ul class="dropdown-menu">
      <li class="header"><h3>Modification des pages</h3></li>
      <li>
        <!-- inner menu: contains the actual data -->
        <ul class="menu">
          <li><!-- Task item -->
            <a href=<"<?= $requestUrl ?>/dashboard">
                Home
            </a>
          </li>
          <!-- end task item -->
          <li><!-- Task item -->
            <a href="<?= $requestUrl ?>/dashboard">
                Reserver
            </a>
          </li>
          <li><!-- Task item -->
            <a href="<?= $requestUrl ?>/dashboard">
                Commander
            </a>
          </li>
          <li><!-- Task item -->
            <a href="<?= $requestUrl ?>/dashboard">
                La Carte
            </a>
          </li>
          <li><!-- Task item -->
            <a href="<?= $requestUrl ?>/dashboard">
                Contact
            </a>
          </li>
          <!-- end task item -->
          <!-- end task item -->
        </ul>
      </li>
    </ul>
  </div>

  <div class="dropdown tasks-menu">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
      Bibliothéque
    </a>
    <ul class="dropdown-menu">
      <li class="header"><h3>Ajouter des item</h3></li>
      <li>
        <!-- inner menu: contains the actual data -->
        <ul class="menu">
          <li><!-- Task item -->
            <a href="<?= $requestUrl ?>/dashboard/produit">
                Produit
            </a>
          </li>
          <!-- end task item -->
          <li><!-- Task item -->
            <a href="<?= $requestUrl ?>/dashboard/clients">
                Photo
            </a>
          </li>
          <li><!-- Task item -->
            <a href="<?= $requestUrl ?>/dashboard/clients">
                Commentaire
            </a>
          <!-- end task item -->
          <!-- end task item -->
        </ul>
      </li>
    </ul>
    <!-- <div class="form-group">
      <input type="text" class="form-control" id="navbar-search-input" placeholder="Search">
    </div>-->
  </div>
