
  <div class="dropdown tasks-menu">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
      Client
    </a>
    <ul class="dropdown-menu">
      <li class="header"><h3>Admin Client</h3></li>
      <li>
        <!-- inner menu: contains the actual data -->
        <ul class="menu">
          <li><!-- Task item -->
            <a href=<"#">
                Liste Client
            </a>
          </li>
          <!-- end task item -->
          <li><!-- Task item -->
            <a href="#">
                Liste Commande
            </a>
          </li>
          <li><!-- Task item -->
            <a href="<?= $requestUrl ?>/dashboard/Reservation">
                Liste Reservation
            </a>
          </li>
          <!-- end task item -->
          <!-- end task item -->
        </ul>
      </li>
    </ul>
  </div>

  <div class="dropdown tasks-menu">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
      Bibliothéque
    </a>
    <ul class="dropdown-menu">
      <li class="header"><h3>Ajouter des produits</h3></li>
      <li>
        <!-- inner menu: contains the actual data -->
        <ul class="menu">
          <li><!-- Task item -->
            <a href="<?= $requestUrl ?>/dashboard/produit">
                Produits
            </a>

          <!-- end task item -->
          <!-- end task item -->
        </ul>
      </li>
    </ul>
    <!-- <div class="form-group">
      <input type="text" class="form-control" id="navbar-search-input" placeholder="Search">
    </div>-->
  </div>
