<div class="dropdown user user-menu menu-top">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown">
    <img src="<?= $wwwUrl."/".$user['url'] ?>" class="user-image" alt="<?= $user['alt'] ?>">
    <span class="hidden-xs"><?= $user['firstName']." ".$user['name'] ?></span>
  </a>
  <div class="dropdown-menu">
    <!-- User image -->
    <li class="user-header">
      <img src="<?= $wwwUrl."/".$user['url'] ?>" class="img-circle img-drpo" alt="<?= $user['alt'] ?>">
      <p>
        <?= $user['firstName']." ".$user['name'] ?>
        <br />
        <small>Membre depuis <?= $user['inscriptionDate'] ?></small>
      </p>
    </li>
    <!-- Menu Body -->
    <li class="user-body">
      <div class="row">
        <div class="col-xs-4 text-center">
          <a href="#">Contact</a>
        </div>
        <div class="col-xs-4 text-center">
          <a href="restaurant/index.php/dashboard/produit">Produit</a>
        </div>
        <div class="col-xs-4 text-center">
          <a href="restaurant/index.php/menu">Menu</a>
        </div>

      </div>
      <!-- /.row -->
    </li>
    <!-- Menu Footer-->
    <li class="user-footer">
      <div class="pull-left">
        <a href="<?= $requestUrl ?>/profile" class="btn btn-primary btn-block btn-flat">Profile</a>
      </div>
      <div class="pull-right">
        <a href="<?= $requestUrl?>/user/logout" class="btn btn-primary btn-block btn-flat">Déconnexion</a>
      </div>
    </li>
  </ul>
</div>
