<div class="dropdown tasks-menu">
  <a href="<?= $requestUrl ?>/menu" class="dropdown-toggle" >
    Reserver
  </a>
</div>
<div class="dropdown tasks-menu">
  <a href="<?= $requestUrl ?>/menu" class="dropdown-toggle" >
  Commander
  </a>
</div>
<div class="dropdown tasks-menu">
  <a href="<?= $requestUrl ?>/menu" class="dropdown-toggle" >
    La carte
  </a>
</div>
<div class="dropdown tasks-menu">
  <a href="<?= $requestUrl ?>/contact" class="dropdown-toggle" >
    Contact
  </a>
  <!--<form class="navbar-form navbar-left" role="search">
    <div class="form-group">
      <input type="text" class="form-control" id="navbar-search-input" placeholder="Search">
    </div>
  </form>-->
</div>
