<div class="dropdown user user-menu menu-top">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown">
    <img src="<?= $wwwUrl."/".$user['Avatar'] ?>" class="user-image" alt="<?= $user['altAvatar'] ?>">
    <span class="hidden-xs"><?= $user['FirstName']." ".$user['LastName'] ?></span>
  </a>
  <div class="dropdown-menu">
    <!-- User image -->
    <li class="user-header">
      <img src="<?= $wwwUrl."/".$user['Avatar'] ?>" class="img-circle img-drpo" alt="<?= $user['altAvatar'] ?>">
      <p>
        <?= $user['FirstName']." ".$user['LastName'] ?>
        <small>Member since <?= $user['InscriptionDate'] ?></small>
      </p>
    </li>
    <!-- Menu Body -->
    <li class="user-body">
      <div class="row">
        <div class="col-xs-4 text-center">
          <a href="#">Commandes</a>
        </div>
        <div class="col-xs-4 text-center">
          <a href="#">Factures</a>
        </div>
        <div class="col-xs-4 text-center">
          <a href="#">lol</a>
        </div>
      </div>
      <!-- /.row -->
    </li>
    <!-- Menu Footer-->
    <li class="user-footer">
      <div class="pull-left">
        <a href="<?= $requestUrl ?>/profile" class="btn btn-default btn-flat">Profile</a>
      </div>
      <div class="pull-right">
        <a href="<?= $requestUrl?>/logout" class="btn btn-default btn-flat">Sign out</a>
      </div>
    </li>
  </ul>
</div>
