<section class="content">
    <div class="row">
      <h2>Enregistrez un produit!</h2>
      <form class="" action="" method="post" enctype="multipart/form-data">
        <select class="" name="type">
          <option value="entrée">Entrée</option>
          <option value="plat">Plat</option>
          <option value="dessert">Dessert</option>
          <option value="boisson">Boisson</option>
          <option value="autre">Autre</option>
        </select>
        <div class="form-group has-feedback">
          <input  class="form-control" type="text" name="name" value="" placeholder="Nom du produit">
          <span class="glyphicon glyphicon-user form-control-feedback"></span>
        </div>
        <div class="form-group has-feedback">
          <textarea  class="form-control" type="text" name="description" value="" placeholder="Description du produit"></textarea>
          <span class="glyphicon glyphicon-user form-control-feedback"></span>
        </div>
        <div class="form-group has-feedback">
          <input  class="form-control" type="text" name="alt" value="" placeholder="Desription photo">
          <span class="glyphicon glyphicon-picture form-control-feedback" ></span>
        </div>
        <div class="form-group has-feedback">
            <input  class="form-control" type="text" name="salePrice" value="" placeholder="Prix de vente">
          <span class="glyphicon glyphicon-euro form-control-feedback" ></span>
        </div>
        <div class="form-group has-feedback">
          <input  class="form-control" type="file" name="url" value="" placeholder="url photo">
          <span class="glyphicon glyphicon-picture form-control-feedback" ></span>
        </div>


	<div class="form-group has-feedback">
            <input  class="form-control" type="submit" value="Enregistrer">
        </div>
      </form>

      <div class="row">
        <div class="col-xs-12">
          <div class="box">
            <div class="box-header">
              <h3 class="box-title">Entrée</h3>

              <div class="box-tools">
                <div class="input-group input-group-sm" style="width: 150px;">
                  <input type="text" name="table_search" class="form-control pull-right" placeholder="Search">

                  <div class="input-group-btn">
                    <button type="submit" class="btn btn-default"><i class="fa fa-search"></i></button>
                  </div>
                </div>
              </div>
            </div>
            <!-- /.box-header -->
            <div class="box-body table-responsive no-padding">
              <table class="table table-hover">
                <tbody><tr>
                  <th>ID</th>
                  <th>Utilisateur</th>
                  <th>Rendez-vous amoureux</th>
                  <th>Statut</th>
                  <th>Raison</th>
                  <th>suprimer</th>
                </tr>
                <tr>
                  <td>183</td>
                  <td>John Doe</td>
                  <td>11-7-2014</td>
                  <td><span class="label label-success">Approuvé</span></td>
                    <td>Bacon ipsum dolor s'asseoir amet salami venaison poulet flanc fatback doner.</td><td><i class="fa fa-times" aria-hidden="true"></i></td>
                </tr>
                <tr>
                  <td>219</td>
                  <td>Alexander Pierce</td>
                  <td>11-7-2014</td>
                  <td><span class="label label-warning">en attendant</span></td>
                    <td>Bacon ipsum dolor s'asseoir amet salami venaison poulet flanc fatback doner.</td><td><i class="fa fa-times" aria-hidden="true"></i></td>
                </tr>
                <tr>
                  <td>657</td>
                  <td>Bob Doe</td>
                  <td>11-7-2014</td>
                  <td><span class="label label-primary">Approuvé</span></td>
                    <td>Bacon ipsum dolor s'asseoir amet salami venaison poulet flanc fatback doner.</td><td><i class="fa fa-times" aria-hidden="true"></i></td>
                </tr>
                <tr>
                  <td>175</td>
                  <td>Mike Doe</td>
                  <td>11-7-2014</td>
                  <td><span class="label label-danger">Refusé</span></td>
                    <td>Bacon ipsum dolor s'asseoir amet salami venaison poulet flanc fatback doner.</td><td><i class="fa fa-times" aria-hidden="true"></i></td>
                </tr>
              </tbody></table>
            </div>
            <!-- /.box-body -->
          </div>
          <!-- /.box -->
        </div>
      </div>
      <div class="row">
        <div class="col-xs-12">
          <div class="box">
            <div class="box-header">
              <h3 class="box-title">Plats</h3>

              <div class="box-tools">
                <div class="input-group input-group-sm" style="width: 150px;">
                  <input type="text" name="table_search" class="form-control pull-right" placeholder="Search">

                  <div class="input-group-btn">
                    <button type="submit" class="btn btn-default"><i class="fa fa-search"></i></button>
                  </div>
                </div>
              </div>
            </div>
            <!-- /.box-header -->
            <div class="box-body table-responsive no-padding">
              <table class="table table-hover">
                <tbody><tr>
                  <th>ID</th>
                  <th>Utilisateur</th>
                  <th>Rendez-vous amoureux</th>
                  <th>Statut</th>
                  <th>Raison</th>
                  <th>suprimer</th>
                </tr>
                <tr>
                  <td>183</td>
                  <td>John Doe</td>
                  <td>11-7-2014</td>
                  <td><span class="label label-success">Approuvé</span></td>
                    <td>Bacon ipsum dolor s'asseoir amet salami venaison poulet flanc fatback doner.</td><td><i class="fa fa-times" aria-hidden="true"></i></td>
                </tr>
                <tr>
                  <td>219</td>
                  <td>Alexander Pierce</td>
                  <td>11-7-2014</td>
                  <td><span class="label label-warning">en attendant</span></td>
                    <td>Bacon ipsum dolor s'asseoir amet salami venaison poulet flanc fatback doner.</td><td><i class="fa fa-times" aria-hidden="true"></i></td>
                </tr>
                <tr>
                  <td>657</td>
                  <td>Bob Doe</td>
                  <td>11-7-2014</td>
                  <td><span class="label label-primary">Approuvé</span></td>
                    <td>Bacon ipsum dolor s'asseoir amet salami venaison poulet flanc fatback doner.</td><td><i class="fa fa-times" aria-hidden="true"></i></td>
                </tr>
                <tr>
                  <td>175</td>
                  <td>Mike Doe</td>
                  <td>11-7-2014</td>
                  <td><span class="label label-danger">Refusé</span></td>
                    <td>Bacon ipsum dolor s'asseoir amet salami venaison poulet flanc fatback doner.</td><td><i class="fa fa-times" aria-hidden="true"></i></td>
                </tr>
              </tbody></table>
            </div>
            <!-- /.box-body -->
          </div>
          <!-- /.box -->
        </div>
      </div>
      <div class="row">
        <div class="col-xs-12">
          <div class="box">
            <div class="box-header">
              <h3 class="box-title">Dessert</h3>

              <div class="box-tools">
                <div class="input-group input-group-sm" style="width: 150px;">
                  <input type="text" name="table_search" class="form-control pull-right" placeholder="Search">

                  <div class="input-group-btn">
                    <button type="submit" class="btn btn-default"><i class="fa fa-search"></i></button>
                  </div>
                </div>
              </div>
            </div>
            <!-- /.box-header -->
            <div class="box-body table-responsive no-padding">
              <table class="table table-hover">
                <tbody><tr>
                  <th>ID</th>
                  <th>Utilisateur</th>
                  <th>Rendez-vous amoureux</th>
                  <th>Statut</th>
                  <th>Raison</th>
                  <th>suprimer</th>
                </tr>
                <tr>
                  <td>183</td>
                  <td>John Doe</td>
                  <td>11-7-2014</td>
                  <td><span class="label label-success">Approuvé</span></td>
                    <td>Bacon ipsum dolor s'asseoir amet salami venaison poulet flanc fatback doner.</td><td><i class="fa fa-times" aria-hidden="true"></i></td>
                </tr>
                <tr>
                  <td>219</td>
                  <td>Alexander Pierce</td>
                  <td>11-7-2014</td>
                  <td><span class="label label-warning">en attendant</span></td>
                    <td>Bacon ipsum dolor s'asseoir amet salami venaison poulet flanc fatback doner.</td><td><i class="fa fa-times" aria-hidden="true"></i></td>
                </tr>
                <tr>
                  <td>657</td>
                  <td>Bob Doe</td>
                  <td>11-7-2014</td>
                  <td><span class="label label-primary">Approuvé</span></td>
                    <td>Bacon ipsum dolor s'asseoir amet salami venaison poulet flanc fatback doner.</td><td><i class="fa fa-times" aria-hidden="true"></i></td>
                </tr>
                <tr>
                  <td>175</td>
                  <td>Mike Doe</td>
                  <td>11-7-2014</td>
                  <td><span class="label label-danger">Refusé</span></td>
                    <td>Bacon ipsum dolor s'asseoir amet salami venaison poulet flanc fatback doner.</td><td><i class="fa fa-times" aria-hidden="true"></i></td>
                </tr>
              </tbody></table>
            </div>
            <!-- /.box-body -->
          </div>
          <!-- /.box -->
        </div>
      </div>
      <div class="row">
        <div class="col-xs-12">
          <div class="box">
            <div class="box-header">
              <h3 class="box-title">Boisson</h3>

              <div class="box-tools">
                <div class="input-group input-group-sm" style="width: 150px;">
                  <input type="text" name="table_search" class="form-control pull-right" placeholder="Search">

                  <div class="input-group-btn">
                    <button type="submit" class="btn btn-default"><i class="fa fa-search"></i></button>
                  </div>
                </div>
              </div>
            </div>
            <!-- /.box-header -->
            <div class="box-body table-responsive no-padding">
              <table class="table table-hover">
                <tbody><tr>
                  <th>ID</th>
                  <th>Utilisateur</th>
                  <th>Rendez-vous amoureux</th>
                  <th>Statut</th>
                  <th>Raison</th>
                  <th>suprimer</th>
                </tr>
                <tr>
                  <td>183</td>
                  <td>John Doe</td>
                  <td>11-7-2014</td>
                  <td><span class="label label-success">Approuvé</span></td>
                    <td>Bacon ipsum dolor s'asseoir amet salami venaison poulet flanc fatback doner.</td>
                    <td><i class="fa fa-times" aria-hidden="true"></i></td>
                </tr>
                <tr>
                  <td>219</td>
                  <td>Alexander Pierce</td>
                  <td>11-7-2014</td>
                  <td><span class="label label-warning">en attendant</span></td>
                    <td>Bacon ipsum dolor s'asseoir amet salami venaison poulet flanc fatback doner.</td>
                    <td><i class="fa fa-times" aria-hidden="true"></i></td>
                </tr>
                <tr>
                  <td>657</td>
                  <td>Bob Doe</td>
                  <td>11-7-2014</td>
                  <td><span class="label label-primary">Approuvé</span></td>
                    <td>Bacon ipsum dolor s'asseoir amet salami venaison poulet flanc fatback doner.</td>
                    <td><i class="fa fa-times" aria-hidden="true"></i></td>
                </tr>
                <tr>
                  <td>175</td>
                  <td>Mike Doe</td>
                  <td>11-7-2014</td>
                  <td><span class="label label-danger">Refusé</span></td>
                    <td>Bacon ipsum dolor s'asseoir amet salami venaison poulet flanc fatback doner.</td><td><i class="fa fa-times" aria-hidden="true"></i></td>
                </tr>
              </tbody></table>
            </div>
            <!-- /.box-body -->
          </div>
          <!-- /.box -->
        </div>
      </div>
