<section class="content">
    <div class="row">
      <h2>Enregistrez un produit!</h2>
      <form class="" action="" method="post" enctype="multipart/form-data">
        <select class="" name="itemType">
          <option forbidden value="------">------</option>
          <option value="entrée">Entrée</option>
          <option value="plat">Plat</option>
          <option value="dessert">Dessert</option>
          <option value="boisson">Boisson</option>
        </select>
        <div class="form-group has-feedback">
          <input  class="form-control" type="text" name="name" value="" placeholder="Nom du produit">
          <span class="glyphicon glyphicon-user form-control-feedback"></span>
        </div>
        <div class="form-group has-feedback">
          <textarea  class="form-control" type="text" name="description" value="" placeholder="Description du produit"></textarea>
          <span class="glyphicon glyphicon-user form-control-feedback"></span>
        </div>
        <div class="form-group has-feedback">
          <input  class="form-control" type="text" name="alt" value="" placeholder="Desription photo">
          <span class="glyphicon glyphicon-picture form-control-feedback" ></span>
        </div>
        <div class="form-group has-feedback">
            <input  class="form-control" type="text" name="salePrice" value="" placeholder="Prix de vente">
          <span class="glyphicon glyphicon-euro form-control-feedback" ></span>
        </div>
        <div class="form-group has-feedback">
          <input  class="form-control" type="file" name="url" value="" placeholder="url photo">
          <span class="glyphicon glyphicon-picture form-control-feedback" ></span>
        </div>


	<div class="form-group has-feedback">
            <input  class="form-control" type="submit" value="Enregistrer">
        </div>
      </form>

      <?php
            foreach ($menu as $key=>$value)
            {
              include(__DIR__."/../../Partiels/ProductTypeView.phtml");
            }
      ?>
